#!/bin/bash
env > /tmp/testenv
#mailmessage="$(cat -)";
#echo "$mailmessage" > /tmp/message

body="0" 
bodytext=""
ip=$1
port=$2

while read line; do
  if ! [ "${line}" = "" ]; then
    if [ "$body" = "0" ]; then
      echo "${line}" >> /tmp/header
    else
      bodytext=$(printf "%s\n%s" $bodytext ${line}) 
    fi    
  else
    body="1"
  fi
done
echo "$bodytext" > /tmp/wholebody
smscmd=$(printf "SENDSMS##%s##%s##%s" "$SENDER" "$LOCAL_PART" "$bodytext")
echo "$smscmd" > /tmp/cmd
res=$(echo "$smscmd" | nc "$ip" "$port")
rescode=$?

echo "$res" > /tmp/res
if ! [ "$rescode" = "0" ]; then
  echo "SMS Feeder not connected, resultcode :"$rescode
  exit 1
fi  

echo "$rescode" > /tmp/resultcode

if [[ $res == "OK"* ]]; then
  echo "$res";
  exit 0
else
  echo "$res";
  exit 2  
fi
